forumLowongan/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', add, name='add'),
]

loginPerusahaan/urls.py
from django.conf.urls import url
from .views import index,add_session,remove_session

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^add-session/$', add_session, name='add-session'),
     url(r'^remove-session/$', remove_session, name='remove-session'),
     
     ]

profilPerusahaan/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index')
]

tanggapanLowongan/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

tugasAkhirPPW/urls.py
from django.contrib import admin
import loginPerusahaan.urls as loginPerusahaan
import tanggapanLowongan.urls as tanggapanLowongan
import forumLowongan.urls as forumLowongan
import profilPerusahaan.urls as profilPerusahaan
from django.views.generic.base import RedirectView
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/login-perusahaan/', permanent="true"), name='go-to-loginPerusahaan'),
    url(r'^profile-perusahaan/', include(profilPerusahaan, namespace='profile-perusahaan')),
    url(r'^login-perusahaan/', include(loginPerusahaan, namespace='login-perusahaan')),
    url(r'^tanggapanLowongan/', include(tanggapanLowongan,namespace='tanggapan-Lowongan')),
    url(r'^forum-lowongan/', include(forumLowongan, namespace='forum-lowongan')),
]

forumLowongan/models.py
from django.db import models

# Create your models here.
class Forum(models.Model):
	title = models.CharField(max_length=140)
	date = models.DateTimeField(auto_now_add=True)
	# company = models.ForeignKey(Company)
	content = models.TextField(max_length=500)
	komentar = []

class Comment(models.Model):
    text = models.CharField(max_length=140)
    content = models.ForeignKey(Forum)
    created_on = models.DateTimeField(auto_now_add=True)

loginPerusahaan/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    id = models.CharField('id', max_length=20, primary_key=True, )
    name = models.CharField('Name', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # komentar = models.CharField('Komentar', max_length=200)

profilPerusahaan/models.py
from django.db import models

# Create your models here.

tanggapanLowongan/models.py
from django.db import models

# Create your models here.

forumLowongan/forms.py
from django import forms

class ForumForm(forms.Form):
    title = forms.CharField(max_length=140)
    content = forms.CharField(max_length=500)

loginPerusahaan/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Insert your description here'
    }

  
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

forumLowongan/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Forum, Comment
from .forms import ForumForm
from loginPerusahaan.views import index
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
response = {}
def index(request):
    if 'user_login' in request.session:
        forum_list = Forum.objects.all()
        #Paginator
        page = request.GET.get('page',1)
        paginate_data = paginate_page(page, forum_list)
        forum = paginate_data['data']
        page_range = paginate_data['page_range']

        response = {"forum_list": forum, "page_range": page_range}
        return render(request, 'forum.html', response)
    else:
        return HttpResponseRedirect(reverse('login-perusahaan:index'))

def paginate_page(page, data_list):
    paginator = Paginator(data_list, 5)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    # Get the index of the current page
    index = data.number - 1
    # This value is maximum index of your pages, so the last page - 1
    max_index = len(paginator.page_range)
    # You want a range of 10, so lets calculate where to slice the list
    start_index = index if index >= 5 else 0
    end_index = 5 if index < max_index - 5 else max_index
    # Get our new page range. In the latest versions of Django page_range returns
    # an iterator. Thus pass it to list, to make our slice possible again.
    page_range = list(paginator.page_range)[start_index:end_index]
    paginate_data = {'data':data, 'page_range':page_range}
    return paginate_data
    

def add(request):
    if request.method == 'POST':
        form = ForumForm(request.POST)
        response['form'] = form
        if form.is_valid():
            Forum.objects.create(content=form.cleaned_data['content'], title=form.cleaned_data['title'])
            forum = Forum.objects.all()
            response['forum'] = forum
            return redirect('/forum-lowongan/')
        else:
            forum = Forum.objects.all()
            response['forum'] = forum
            response['form'] = form
            return render(request, 'daftar_login.html', response)
    return redirect('/forum-lowongan/')

def delete_forum(request, id):
    to_delete = Forum.objects.get(id=id)
    to_delete.delete()
    return redirect('/forum-lowongan/')

loginPerusahaan/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .models import User
from forumLowongan.models import Forum, Comment
# Create your views here.
response={}
def index(request):
    response['author'] = "Rai Indhira" #TODO Implement yourname
    html = 'daftar_login.html'

    readData = User.objects.all()
    readForum = Forum.objects.all()

    response['dataUser'] = readData
    response['forumLowongan'] = readForum
    print(User.objects.all().values_list('name', flat=True) )
    return render(request, html, response)

def add_session(request):
    if request.method == 'POST':
        name = request.POST['name']
        id = request.POST['id']
        request.session['user_login'] = id
        request.session['name'] = name
        try:
            user = User.objects.get(id = id)
        except Exception as e:
            user = User()
            user.id = id
            user.name = name
            user.save()
        return HttpResponseRedirect(reverse('login-perusahaan:index'))

def remove_session(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('fitur-login:index'))

profilPerusahaan/views.py
from django.shortcuts import render


# Create your views here.

response = {}

def index(request):
    html = 'profile.html'
    return render(request, html, response)

tanggapanLowongan/views.py
from __future__ import unicode_literals

import json

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

response = {}

# Create your views here.

### USER
def index(request):
    # print ("#==> masuk index")
    
    return render(request, 'tanggapanLowongan.html', response)


    

forumLowongan/templates/forum.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
  Forum Lowongan
{% endblock %}

{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}" />
  <style>
    .desain_footer{
      position: absolute;
    }
  </style>
{% endblock %}

{% block content %}
    <!-- Main body -->
    <div class="container">
      <div class="row">
          <div class="col-sm-7">
              <h3>Forum</h3>
              <h4 class="card-title"> Post Forum </h4>
              <div class="card">
                  <div class="card-block">

                      <!-- Form for new status -->
                      <form class="card-text" method="POST" action="{% url 'forum-lowongan:add' %}">
                          {% csrf_token %}
                          <h5 class="card-title" style="font-family: Goudy Old Style"> Title </h5>
                          <input class="form-control" name="title" id="title" title="title"/>
                          <h5 class="card-title" style="margin-top: 10px; font-family: Goudy Old Style"> Content </h5>
                          <input class="form-control" name="content" id="content" title="content"/>
                  </div>
              </div>
              <button type="submit" class="btn btn-primary float-right" style="margin-top: 2px" id="button">Post</button>
            </form>
          </div>
      </div>
  </div>

  <!-- Print errors if any -->
  {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
  {% endif %}


                        
 <div class="container forums">
    {% for i in forum_list reversed %}
        <div class="flex-item">
            <div class="forum content">
                <h5> {{ i.title }} </h5>
                <sub> {{ i.date }} </sub>
                <p> {{ i.content }} </p>
            </div>
        </div>
    {% endfor %}
</div>
                    {% if forum_list.has_other_pages %}
                      <ul class="pagination">
                        {% if forum_list.has_previous %}
                          <li><a href="?page={{ forum_list.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                          <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in forum_list.paginator.page_range %}
                          {% if forum_list.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                          {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                          {% endif %}
                        {% endfor %}
                        {% if forum_list.has_next %}
                          <li><a href="?page={{ forum_list.next_page_number }}">&raquo;</a></li>
                        {% else %}
                          <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                      </ul>
                    {% endif %}
                    {% if auth %}
                        <div id="token" hidden="true">{{ auth.access_token }}</div>
                        <div id="cid" hidden="true">{{ auth.client_id }}</div>
                    {% endif %}
                </div>
            </div>
 
{% endblock %}

{% block javascript %}

{% endblock %}

loginPerusahaan/templates/daftar_login.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
{% block css %}
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<body>
<style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
    body, html {
        height: 100%;
        line-height: 0;
        background-image: url('https://i.imgur.com/ugNmG8t.png');
        background-position: center;
        background-size: cover;
        min-height: 100%;
    }
    /* Full height image header */
    .bgimg-1 {
        margin-top: 150px;
    }
    .w3-bar .w3-button {
        padding: 50%;
    }
    .dataLowongan{

      margin-top: 50px;

      background-color: #d5f4e6;
      padding-left: 100px;
      padding-bottom: 50px;
      
    }
    #data{
    margin-right: 200px;
    margin-bottom: 10px;
    border: 10px solid white;
    padding: 10px;
    
    }
    #judul{
      margin-top: 25px;
    }
    #date{
      margin-top: 25px;
    }
    #message{
      margin-top: 25px;
    }
    #isiMessage{
      margin-top: 50px;
      margin-left: 30px;
      background-color: #fefbd8;
      font-size: 150%;

    }
    #komentar{
      margin-top: 25px;

    }
    
</style>

<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-card" id="myNavbar">
    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
    </div>
    <!-- Hide right-floated links on small screens and replace them with a menu icon -->

    <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium" onclick="w3_open()">
      <i class="fa fa-bars"></i>
    </a>
  </div>
</div>

<!-- Sidebar on small screens when clicking the menu icon -->
<nav class="w3-sidebar w3-bar-block w3-black w3-card w3-animate-left w3-hide-medium w3-hide-large" style="display:none" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-large w3-padding-16">Close ×</a>
  <a href="#about" onclick="w3_close()" class="w3-bar-item w3-button">ABOUT</a>
  <a href="#team" onclick="w3_close()" class="w3-bar-item w3-button">TEAM</a>
  <a href="#work" onclick="w3_close()" class="w3-bar-item w3-button">WORK</a>
  <a href="#pricing" onclick="w3_close()" class="w3-bar-item w3-button">PRICING</a>
  <a href="#contact" onclick="w3_close()" class="w3-bar-item w3-button">CONTACT</a>
</nav>

<!-- Header with full-height image -->
<header class="bgimg-1 w3-display-container w3-grayscale-min" id="home">
  <div class="w3-display-left w3-text-black" style="padding:48px">
    <span class="w3-jumbo w3-hide-small">Welcome to our project</span><br>
    <span class="w3-xxlarge w3-hide-large w3-hide-medium">Start something that matters</span><br>
  </div> 
  <div class="w3-display-bottomleft w3-text-grey w3-large" style="padding:24px 48px">
  </div>
</header>

</body>
</html>

<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key:   81hmr79d53455z
    onLoad:    onLinkedInLoadCompany
    authorize: true
</script>

{% endblock %}
<center>
    <div id="lab8" >
      {% csrf_token %}
        <script type="in/Login"></script>
    </div></center>
	<div id="profileData">
  <div id="gambar"></div>
	<div id="name"></div>
	<div id="tempat"></div>
	</div>
	<div id="logout">

	</div>

  </br>
  </br>


  <div class='dataLowongan'>
<   {% for data in dataUser%}
    {{data.id}}
    {{data.name}}
    {{data.created_at}}
    </br>
    {{data.komentar}}



  
    <br>
    <p id="test"></p>
  {% endfor %}

</br>
  
  <h1> DATA DARI FORUM LOWONGAN</h1>
  
 {% for x in forumLowongan%}
 <div id = 'data'>
    <div id ='judul'> Judul : {{x.title}} </br> </div>
    <div id ='date'>Date : {{x.date}} </br></div>
    <div id ='message'>Lowongan : </br> </div>
    <div id= 'isiMessage'> {{x.content}} </br> </div>
    </br>
   <div id ='komentar'> {{x.komentar}} </br>

    </br>

    <form  onsubmit="tambahKomentar(this.form)">
      Insert Komentar: <input id="komentar"type="text" name="fname">
     <input type="submit" value="Submit">
    </form>
    </br>
  </div>
  </div>
  {% endfor %}
  


</div>


{% endblock %}
{% block javascript %}
<script>// Setup an event listener to make an API call once auth is complete

function tambahKomentar(form){
  
}



function onLinkedInLoad() {
    IN.Event.on(IN, "auth", getProfileData);
}

// Use the API call wrapper to request the member's profile data
function getProfileData() {
    IN.API.Profile("me").fields("id", "first-name", "last-name", "headline", "location", "picture-url", "public-profile-url",
"email-address").result(displayProfileData).error(onError);
}

// Handle the successful return from the API call
function displayProfileData(data){
  var user = data.values[0];
  var id = user.id;
  console.log(id);
  $.ajax({
      method: "POST",
      url: '{% url "login-perusahaan:add-session" %}',
      data: { name: user.firstName+" "+user.lastName, id: id, csrfmiddlewaretoken: '{{ csrf_token }}'},
      success : function () {
      },
      error : function (error) {
          alert("Account ini tidak memiliki izin")
      }
  });
  $("#gambar").append('<img src="'+user.pictureUrl+'"class="img-circle">');
  $("#name").append('<b>'+user.firstName+' '+user.lastName+'</b><br>'+user.headline );
	$("#tempat").append(user.location.name);
	$("#logout").append("<button class='btn btn-danger' onClick='logout()'>Logout</button>");
	console.log(data);
	console.log();
}

// Handle an error response from the API call
function onError(error) {
    console.log(error);
}

// Destroy the session of linkedin
function logout(){
    IN.User.logout(logoutYuk);
}

// Remove profile data from page
function logoutYuk(){
	window.location.assign("{% url 'login-perusahaan:index'%}")
  $.ajax({
      method: "GET",
      url: '{% url "login-perusahaan:remove-session" %}',

});
}
</script>
{% endblock %}

profilPerusahaan/templates/profile.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Profile</title>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}"/>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <script type="text/javascript" src="//platform.linkedin.com/in.js">
          api_key: 81hmr79d53455z
          authorize: true
          onLoad: onLinkedInLoad
        </script>
    </head>
    <body>
        <script src="{% static 'js/profile.js' %}"></script>
        <div id="profileData">
            <p><a href="{% url 'login-perusahaan:index' %}" onclick="logout()">Logout</a></p>
            <div id="picture"></div>
            <center><a href= {%  url 'forum-lowongan:index' %} class="head-button">Lihat Forum</a></center>
            <div class="company">
                <h3>Company Name:</h3>
                <p id="companyName"></p>
                <h3>Description:</h3>
                <p id="description"></p>
                <h3>Company Type</h3>
                <p id="companyType"></p>
                <h3>Specialties</h3>
                <p id="specialties"></p>
                <p id="location"></p>

            </div>
        </div>
    </body>
<header>
    {% block header %}
    {% include 'partials/header.html' %}
    {% endblock %}
</header>

<footer>
    {% block footer %}
        {% include 'partials/footer.html' %}
    {% endblock %}
</footer>
</html>

tanggapanLowongan/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 5">
    <meta name="author" content="{{author}}">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lab_6.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">


    <title>
        {% block title %} Lab 6 By {{author}} {% endblock %}
    </title>
</head>
<body>
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}


    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'js/lab_6.js' %}"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
</body>

tanggapanLowongan/templates/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<!-- <p>Made with Love by {{author}}</p> -->
 
 <p style="font-family:courier;"><center> Made with Love by &copy; {{author}}</center></p>

tanggapanLowongan/templates/partials/header.html
<!-- templates/lab_5/partials/header.html -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a >Input Todo</a></li>
        
       
         <id="header-logo"> <img src=" https://scele.cs.ui.ac.id/pluginfile.php/1/theme_lambda/logo/1502278612/5.png"/> </id>
        


       
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

tanggapanLowongan/templates/tanggapanLowongan.html
{% extends "layout/base.html" %}

{% block content %}


<h1> ando </h1>
{% endblock %}

templates/base.html
{% load staticfiles %}
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="TUGAS 2">
    <meta name="author" content="{{author}}">

    <!-- bootstrap csss -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.6.2.js"></script>
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key:   81hmr79d53455z
    onLoad:    onLinkedInLoad
    authorize: true
    </script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/loginPerusahaan.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    <title>
        {% block title %} TUGAS 2 {% endblock %}
    </title>
</head>
<body>
<header>
    {% block header %}
    {% include "partials/header.html" %}
    {% endblock %}
</header>
<content>
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
<footer>
    <hr>
    {% block footer %}
        {% include 'partials/footer.html' %}
    {% endblock %}
</footer>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

templates/partials/footer.html
<div class="container">
    <center>
 	<p>© 2017<a style="color:#403831; text-decoration:none;" href="#"> PPWFun Team</a>, All rights reserved 2017-2018.</p>
    </center>
</div>

templates/partials/header.html
<nav class="navbar navbar-default navbar-fixed-top sticky" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">PPWFun</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav" style="float: right" id="navbar-right-menu" >
        <li><a href="/profile-perusahaan">Profile</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>